import Head from 'next/head';
import Image from 'next/image';
import { Lato } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const lato = Lato({ subsets: ['latin'], weight: '400' });

export default function Home() {
  return (
    <>
      <Head>
        <title>React Weather API App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${styles.main} ${lato.className}`}>
        <div className={styles.container}>
          <div className={styles.top_bar}>
            <div className={styles.location}>
              <p>Nottingham</p>
            </div>
            <div className={styles.search_container}>
              <input
                type="text"
                placeholder="search"
              />
            </div>
          </div>
          <div className={styles.weather_type_container}>
            <p>Icon here</p>
            <p>Sunny</p>
          </div>
          <div className={styles.weather_info_container}>
            <div className={styles.weather_detail}>
              <p>21 m/s</p>
              <p>13%</p>
              <p>4%</p>
            </div>
            <div className={styles.temperature}>22</div>
          </div>
        </div>
      </main>
    </>
  );
}
